language: java
sudo: false
jdk:
   - oraclejdk8
script:
  - ./gradlew clean build
branches:
  only:
    - master
    - develop
    - /^feature.*$/
    - /^hotfix.*$/
notifications:
  email: false
deploy:
  provider: openshift
  user: w.cheizoo@gmail.com
  password: 42554255
  domain: hetzijzo
  app: strucdocs
  on: develop
